from fastapi import APIRouter

from glasshaus.api.errors import PROBLEM_RESPONSES
from glasshaus.api.v1 import (
    admin,
    ai,
    assistant,
    auth,
    automation,
    collab,
    fields,
    goals,
    imports,
    insights,
    integrations,
    oauth,
    onboarding,
    projects,
    push,
    reports,
    scheduling,
    sso,
    tasks,
    team,
    timetracking,
    users,
    views,
    workspaces,
)

api_router = APIRouter(prefix="/api/v1", responses=PROBLEM_RESPONSES)
for module in (
    auth,
    users,
    workspaces,
    projects,
    fields,
    views,
    tasks,
    imports,
    scheduling,
    collab,
    automation,
    timetracking,
    insights,
    reports,
    assistant,
    goals,
    oauth,
    onboarding,
    push,
    admin,
    ai,
    sso,
    integrations,
    team,
):
    api_router.include_router(module.router)
