"""Idempotent baseline data and a deterministic demo-data generator (built on the service layer)."""

import random
import uuid
from datetime import date, timedelta

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from glasshaus.collab import service as collab
from glasshaus.collab.schemas import CommentCreate
from glasshaus.config import get_settings
from glasshaus.core.context import Actor
from glasshaus.db import apply_tenant, system_session, unit_of_work
from glasshaus.fields import service as fields
from glasshaus.fields.schemas import FieldCreate, SelectOption
from glasshaus.identity import service as identity
from glasshaus.identity.models import User, Workspace
from glasshaus.identity.schemas import UserCreate, WorkspaceCreate, WorkspaceMemberSet
from glasshaus.logs import get_logger
from glasshaus.models import Tenant
from glasshaus.projects import service as projects
from glasshaus.projects.schemas import ProjectCreate
from glasshaus.tasks import service as tasks
from glasshaus.tasks.models import Priority
from glasshaus.tasks.schemas import TaskCreate, TaskUpdate
from glasshaus.views import service as views
from glasshaus.views.schemas import ViewConfig, ViewCreate, ViewFilters

log = get_logger(__name__)
DEMO_WORKSPACE = "demo"


async def ensure_default_tenant(session: AsyncSession) -> Tenant:
    settings = get_settings()
    tenant = await session.scalar(select(Tenant).where(Tenant.slug == settings.default_tenant_slug))
    if tenant is None:
        tenant = Tenant(slug=settings.default_tenant_slug, name=settings.default_tenant_name)
        session.add(tenant)
        await session.flush()
        log.info("seed.tenant.created", slug=tenant.slug)
    return tenant


async def ensure_admin(session: AsyncSession, tenant: Tenant) -> User | None:
    settings = get_settings()
    if settings.admin_password is None:
        log.warning("seed.admin.skipped", reason="GLASSHAUS_ADMIN_PASSWORD not set")
        return None
    user = await identity.ensure_owner(
        session,
        tenant,
        email=settings.admin_email,
        password=settings.admin_password.get_secret_value(),
        name=settings.admin_name,
    )
    await apply_tenant(session, None, bypass_rls=True)
    return user


async def generate_demo_data(tenant: Tenant, owner: User, seed: int) -> None:
    from faker import Faker

    fake = Faker("en_CA")
    Faker.seed(seed)
    rng = random.Random(seed)  # noqa: S311 - deterministic demo data, not security
    actor = Actor(tenant_id=tenant.id, user_id=owner.id, org_role=owner.org_role, method="system")
    async with unit_of_work(actor) as ctx:
        if await ctx.session.scalar(select(Workspace.id).where(Workspace.slug == DEMO_WORKSPACE)):
            log.info("seed.demo.exists")
            return
        ws = await identity.create_workspace(
            ctx,
            WorkspaceCreate(name="Demo", slug=DEMO_WORKSPACE, description="Sample data generated by seed"),
        )
        people = []
        for i in range(6):
            user = await identity.create_user(
                ctx, UserCreate(email=f"demo{i + 1}@example.com", name=fake.name(), password=None)
            )
            await identity.set_workspace_member(
                ctx, ws.id, WorkspaceMemberSet(user_id=user.id, role="member")
            )
            people.append(user.id)
        today = date.today()
        for key, name in (("WEB", "Website relaunch"), ("OPS", "Homelab operations"), ("MOB", "Mobile app")):
            project = await projects.create_project(
                ctx, ProjectCreate(workspace_id=ws.id, key=key, name=name, description=fake.paragraph())
            )
            severity = await fields.create_field(
                ctx,
                project.id,
                FieldCreate(
                    name="Severity",
                    type="select",
                    options=[SelectOption(id=f"s{i}", label=f"Sev {i}") for i in (1, 2, 3)],
                ),
            )
            points = await fields.create_field(
                ctx, project.id, FieldCreate(name="Story points", type="number")
            )
            await views.create_view(
                ctx,
                project.id,
                ViewCreate(
                    name="Team board",
                    kind="board",
                    shared=True,
                    config=ViewConfig(group_by="status"),
                ),
            )
            await views.create_view(
                ctx,
                project.id,
                ViewCreate(
                    name="Urgent work",
                    kind="table",
                    shared=True,
                    config=ViewConfig(
                        filters=ViewFilters(priorities=["urgent", "high"]),
                        columns=["key", "title", "status", "assignee", "due_date", f"cf:{severity.id}"],
                    ),
                ),
            )
            parents: list[uuid.UUID] = []
            for _ in range(rng.randint(18, 30)):
                start = today + timedelta(days=rng.randint(-20, 30))
                task = await tasks.create_task(
                    ctx,
                    TaskCreate(
                        project_id=project.id,
                        title=fake.sentence(nb_words=rng.randint(3, 8)).rstrip("."),
                        description=fake.paragraph(nb_sentences=3),
                        priority=rng.choice(list(Priority)),
                        assignee_id=rng.choice([*people, None]),
                        parent_id=rng.choice(parents) if parents and rng.random() < 0.25 else None,
                        start_date=start,
                        due_date=start + timedelta(days=rng.randint(1, 21)),
                        estimate_minutes=rng.choice([None, 30, 60, 120, 240, 480]),
                        tags=rng.sample(
                            ["frontend", "backend", "infra", "design", "bug", "docs"], k=rng.randint(0, 2)
                        ),
                        custom_fields={
                            str(severity.id): rng.choice(["s1", "s2", "s3"]),
                            str(points.id): rng.choice([1, 2, 3, 5, 8]),
                        },
                    ),
                )
                if rng.random() < 0.3:
                    who = rng.choice(people)
                    body = f"{fake.sentence()} @[{fake.first_name()}](user:{who})"
                    await collab.create_comment(ctx, task.id, CommentCreate(body=body))
                if task.parent_id is None:
                    parents.append(task.id)
                status = rng.choice(project.statuses)
                await tasks.update_task(ctx, task.id, TaskUpdate(status_id=status.id))
    log.info("seed.demo.created")


async def run_seed(*, demo: bool = False, seed: int = 42) -> None:
    async with system_session() as session:
        tenant = await ensure_default_tenant(session)
        owner = await ensure_admin(session, tenant)
    if demo:
        if owner is None:
            raise SystemExit("demo data needs an owner: set GLASSHAUS_ADMIN_PASSWORD")
        await generate_demo_data(tenant, owner, seed)
