"""Idempotent baseline data and a deterministic demo-data generator (built on the service layer)."""

import itertools
import random
import uuid
from datetime import date, timedelta

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from glasshaus.automation import service as automation
from glasshaus.automation import templates
from glasshaus.automation.schemas import RecurringCreate, RuleCreate, TemplateCreate
from glasshaus.collab import service as collab
from glasshaus.collab.schemas import CommentCreate
from glasshaus.config import get_settings
from glasshaus.core.context import Actor, ServiceContext
from glasshaus.core.rbac import OrgRole
from glasshaus.db import apply_tenant, system_session, unit_of_work
from glasshaus.fields import service as fields
from glasshaus.fields.schemas import FieldCreate, SelectOption
from glasshaus.goals import service as goals
from glasshaus.goals.schemas import ObjectiveCreate, PortfolioCreate
from glasshaus.identity import service as identity
from glasshaus.identity.models import User, Workspace
from glasshaus.identity.schemas import UserCreate, WorkspaceCreate, WorkspaceMemberSet
from glasshaus.insights import service as insights
from glasshaus.insights.schemas import DashboardCreate
from glasshaus.logs import get_logger
from glasshaus.models import Tenant
from glasshaus.projects import service as projects
from glasshaus.projects.schemas import ProjectCreate
from glasshaus.scheduling import service as scheduling
from glasshaus.scheduling.schemas import BaselineCreate, DependencyCreate
from glasshaus.tasks import service as tasks
from glasshaus.tasks.models import Priority
from glasshaus.tasks.schemas import TaskCreate, TaskUpdate
from glasshaus.timetracking import service as timetracking
from glasshaus.timetracking.schemas import TimeEntryCreate
from glasshaus.views import service as views
from glasshaus.views.schemas import ViewConfig, ViewCreate, ViewFilters

log = get_logger(__name__)
DEMO_WORKSPACE = "demo"


async def ensure_default_tenant(session: AsyncSession) -> Tenant:
    settings = get_settings()
    tenant = await session.scalar(select(Tenant).where(Tenant.slug == settings.default_tenant_slug))
    if tenant is None:
        tenant = Tenant(slug=settings.default_tenant_slug, name=settings.default_tenant_name)
        session.add(tenant)
        await session.flush()
        log.info("seed.tenant.created", slug=tenant.slug)
    return tenant


async def ensure_admin(session: AsyncSession, tenant: Tenant) -> User | None:
    settings = get_settings()
    if settings.admin_password is None:
        log.warning("seed.admin.skipped", reason="GLASSHAUS_ADMIN_PASSWORD not set")
        return None
    user = await identity.ensure_owner(
        session,
        tenant,
        email=settings.admin_email,
        password=settings.admin_password.get_secret_value(),
        name=settings.admin_name,
    )
    await apply_tenant(session, None, bypass_rls=True)
    return user


async def generate_demo_data(tenant: Tenant, owner: User, seed: int) -> None:
    from faker import Faker

    fake = Faker("en_CA")
    Faker.seed(seed)
    rng = random.Random(seed)  # noqa: S311 - deterministic demo data, not security
    actor = Actor(tenant_id=tenant.id, user_id=owner.id, org_role=owner.org_role, method="system")
    async with unit_of_work(actor) as ctx:
        if await ctx.session.scalar(select(Workspace.id).where(Workspace.slug == DEMO_WORKSPACE)):
            log.info("seed.demo.exists")
            return
        ws = await identity.create_workspace(
            ctx,
            WorkspaceCreate(name="Demo", slug=DEMO_WORKSPACE, description="Sample data generated by seed"),
        )
        people = []
        for i in range(6):
            user = await identity.create_user(
                ctx, UserCreate(email=f"demo{i + 1}@example.com", name=fake.name(), password=None)
            )
            await identity.set_workspace_member(
                ctx, ws.id, WorkspaceMemberSet(user_id=user.id, role="member")
            )
            people.append(user.id)
        today = date.today()
        project_ids: list[uuid.UUID] = []
        web_id: uuid.UUID | None = None
        for key, name in (("WEB", "Website relaunch"), ("OPS", "Homelab operations"), ("MOB", "Mobile app")):
            project = await projects.create_project(
                ctx, ProjectCreate(workspace_id=ws.id, key=key, name=name, description=fake.paragraph())
            )
            severity = await fields.create_field(
                ctx,
                project.id,
                FieldCreate(
                    name="Severity",
                    type="select",
                    options=[SelectOption(id=f"s{i}", label=f"Sev {i}") for i in (1, 2, 3)],
                ),
            )
            points = await fields.create_field(
                ctx, project.id, FieldCreate(name="Story points", type="number")
            )
            await views.create_view(
                ctx,
                project.id,
                ViewCreate(
                    name="Team board",
                    kind="board",
                    shared=True,
                    config=ViewConfig(group_by="status"),
                ),
            )
            await views.create_view(
                ctx,
                project.id,
                ViewCreate(
                    name="Urgent work",
                    kind="table",
                    shared=True,
                    config=ViewConfig(
                        filters=ViewFilters(priorities=["urgent", "high"]),
                        columns=["key", "title", "status", "assignee", "due_date", f"cf:{severity.id}"],
                    ),
                ),
            )
            parents: list[uuid.UUID] = []
            created: list[uuid.UUID] = []
            for _ in range(rng.randint(18, 30)):
                start = today + timedelta(days=rng.randint(-20, 30))
                task = await tasks.create_task(
                    ctx,
                    TaskCreate(
                        project_id=project.id,
                        title=fake.sentence(nb_words=rng.randint(3, 8)).rstrip("."),
                        description=fake.paragraph(nb_sentences=3),
                        priority=rng.choice(list(Priority)),
                        assignee_id=rng.choice([*people, None]),
                        parent_id=rng.choice(parents) if parents and rng.random() < 0.25 else None,
                        start_date=start,
                        due_date=start + timedelta(days=rng.randint(1, 21)),
                        estimate_minutes=rng.choice([None, 30, 60, 120, 240, 480]),
                        tags=rng.sample(
                            ["frontend", "backend", "infra", "design", "bug", "docs"], k=rng.randint(0, 2)
                        ),
                        custom_fields={
                            str(severity.id): rng.choice(["s1", "s2", "s3"]),
                            str(points.id): rng.choice([1, 2, 3, 5, 8]),
                        },
                    ),
                )
                if rng.random() < 0.3:
                    who = rng.choice(people)
                    body = f"{fake.sentence()} @[{fake.first_name()}](user:{who})"
                    await collab.create_comment(ctx, task.id, CommentCreate(body=body))
                created.append(task.id)
                if task.parent_id is None:
                    parents.append(task.id)
                status = rng.choice(project.statuses)
                await tasks.update_task(ctx, task.id, TaskUpdate(status_id=status.id))
            # A finish-to-start chain through a few top-level tasks (ordered by start, so acyclic).
            top = [await tasks.get_task(ctx, pid) for pid in parents[:12]]
            chain = sorted([t for t in top if t.start_date], key=lambda t: t.start_date or today)[:6]
            for pred, succ in itertools.pairwise(chain):
                await scheduling.create_dependency(
                    ctx,
                    DependencyCreate(
                        predecessor=str(pred.id), successor=str(succ.id), lag_days=rng.choice([0, 0, 1])
                    ),
                )
            await scheduling.create_baseline(ctx, project.id, BaselineCreate(name="Initial plan"))
            await automation.create_rule(
                ctx,
                project.id,
                RuleCreate.model_validate(
                    {
                        "name": "Thank the team when work ships",
                        "trigger": {"type": "status_changed", "to_category": "done"},
                        "conditions": [{"field": "priority", "op": "in", "value": ["high", "urgent"]}],
                        "actions": [
                            {"type": "add_tags", "tags": ["shipped"]},
                            {"type": "post_comment", "body": "{{task.key}} shipped. Nice work!"},
                        ],
                    }
                ),
            )
            await automation.create_rule(
                ctx,
                project.id,
                RuleCreate.model_validate(
                    {
                        "name": "Due tomorrow reminder",
                        "trigger": {"type": "due_soon", "days_before": 1},
                        "actions": [
                            {"type": "notify", "users": ["assignee"], "title": "{{task.key}} is due tomorrow"}
                        ],
                    }
                ),
            )
            await automation.create_recurring(
                ctx,
                project.id,
                RecurringCreate.model_validate(
                    {
                        "template": {"title": f"Weekly {key} review", "tags": ["review"], "due_in_days": 1},
                        "schedule": {
                            "frequency": "weekly",
                            "weekday": 0,
                            "hour": 9,
                            "timezone": "America/Toronto",
                        },
                    }
                ),
            )
            project_ids.append(project.id)
            # A few weeks of time logged by the team, each entry as its author.
            for task_id in rng.sample(created, k=min(len(created), 12)):
                who = rng.choice(people)
                as_person = ServiceContext(
                    session=ctx.session,
                    actor=Actor(tenant_id=tenant.id, user_id=who, org_role=OrgRole.MEMBER, method="system"),
                )
                for _ in range(rng.randint(1, 3)):
                    await timetracking.log_time(
                        as_person,
                        TimeEntryCreate(
                            task=str(task_id),
                            spent_on=today - timedelta(days=rng.randint(0, 20)),
                            minutes=rng.choice([15, 30, 45, 60, 90, 120, 240]),
                            note=rng.choice(["", "pairing", "review", "investigation"]),
                            billable=rng.random() < 0.4,
                        ),
                    )
            if key == "WEB":
                web_id = project.id
                await templates.create_template(
                    ctx,
                    TemplateCreate(
                        project_id=project.id,
                        name="Website launch",
                        description="Statuses, fields, views, tasks and automations from the demo website.",
                    ),
                )
        await goals.create_portfolio(ctx, PortfolioCreate(name="All demo projects", project_ids=project_ids))
        quarter = f"{today.year}-Q{(today.month - 1) // 3 + 1}"
        await goals.create_objective(
            ctx,
            ObjectiveCreate.model_validate(
                {
                    "title": "Relaunch the website",
                    "period": quarter,
                    "key_results": [
                        {"title": "Launch tasks done", "kind": "tasks", "project_id": str(web_id)},
                        {
                            "title": "Newsletter sign-ups",
                            "kind": "metric",
                            "start_value": 200,
                            "target_value": 1000,
                            "current_value": 420,
                            "unit": "people",
                        },
                    ],
                }
            ),
        )
        await insights.create_dashboard(
            ctx,
            DashboardCreate.model_validate(
                {
                    "name": "Team overview",
                    "shared": True,
                    "widgets": [
                        {"id": "tasks", "type": "my_tasks", "width": 2},
                        {"id": "time", "type": "my_time"},
                        {"id": "burnup", "type": "burnup", "width": 2, "config": {"project_id": str(web_id)}},
                        {"id": "workload", "type": "workload"},
                        {"id": "byproject", "type": "time_by_project", "width": 3},
                    ],
                }
            ),
        )
    log.info("seed.demo.created")


async def run_seed(*, demo: bool = False, seed: int = 42) -> None:
    async with system_session() as session:
        tenant = await ensure_default_tenant(session)
        owner = await ensure_admin(session, tenant)
    if demo:
        if owner is None:
            raise SystemExit("demo data needs an owner: set GLASSHAUS_ADMIN_PASSWORD")
        await generate_demo_data(tenant, owner, seed)
