"""reporting lines and directory sync

Revision ID: 40f70796584f
Revises: 2f9c61b24281
Create Date: 2026-10-10 00:01:29.980179+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "40f70796584f"
down_revision: str | Sequence[str] | None = "2f9c61b24281"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directory_syncs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("directory_id", sa.String(length=100), server_default="", nullable=False),
        sa.Column("client_id", sa.String(length=100), server_default="", nullable=False),
        sa.Column("client_secret", sa.String(length=1000), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column(
            "last_result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_directory_syncs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_directory_syncs")),
    )
    enable_rls("directory_syncs")
    op.add_column(
        "org_settings",
        sa.Column("manager_visibility", sa.String(length=10), server_default="all", nullable=False),
    )
    op.add_column("users", sa.Column("manager_id", sa.Uuid(), nullable=True))
    op.add_column("users", sa.Column("manager_source", sa.String(length=10), nullable=True))
    op.add_column("users", sa.Column("job_title", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("department", sa.String(length=200), nullable=True))
    op.create_index(op.f("ix_users_manager_id"), "users", ["manager_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_users_manager_id_users"), "users", "users", ["manager_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_manager_id_users"), "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_manager_id"), table_name="users")
    op.drop_column("users", "department")
    op.drop_column("users", "job_title")
    op.drop_column("users", "manager_source")
    op.drop_column("users", "manager_id")
    op.drop_column("org_settings", "manager_visibility")
    disable_rls("directory_syncs")
    op.drop_table("directory_syncs")
    # ### end Alembic commands ###
