"""report subscriptions

Revision ID: c386c5964fc6
Revises: 7c54ac7de5d2
Create Date: 2026-10-09 15:32:44.918589+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "c386c5964fc6"
down_revision: str | Sequence[str] | None = "7c54ac7de5d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_subscriptions",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attach_csv", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["saved_reports.id"],
            name=op.f("fk_report_subscriptions_report_id_saved_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_report_subscriptions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_report_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_subscriptions")),
        sa.UniqueConstraint("report_id", "user_id", name=op.f("uq_report_subscriptions_report_id_user_id")),
    )
    op.create_index(
        op.f("ix_report_subscriptions_next_run_at"), "report_subscriptions", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_report_subscriptions_report_id"), "report_subscriptions", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_subscriptions_tenant_id"), "report_subscriptions", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_subscriptions_user_id"), "report_subscriptions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
    enable_rls("report_subscriptions")


def downgrade() -> None:
    """Downgrade schema."""
    disable_rls("report_subscriptions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_subscriptions_user_id"), table_name="report_subscriptions")
    op.drop_index(op.f("ix_report_subscriptions_tenant_id"), table_name="report_subscriptions")
    op.drop_index(op.f("ix_report_subscriptions_report_id"), table_name="report_subscriptions")
    op.drop_index(op.f("ix_report_subscriptions_next_run_at"), table_name="report_subscriptions")
    op.drop_table("report_subscriptions")
    # ### end Alembic commands ###
