"""sso link existing accounts

Revision ID: 4485c026e30e
Revises: 4264c5dbb4ae
Create Date: 2026-10-08 22:59:21.374129+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4485c026e30e"
down_revision: str | Sequence[str] | None = "4264c5dbb4ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "identity_providers",
        sa.Column("link_existing_accounts", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("identity_providers", "link_existing_accounts")
    # ### end Alembic commands ###
