"""search and activity indexes

Revision ID: 4b9e1ba756c7
Revises: e991a20d86ef
Create Date: 2026-10-10 10:21:57.282585+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b9e1ba756c7"
down_revision: str | Sequence[str] | None = "e991a20d86ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Trigram matching for title search (a trusted extension: the database owner may create it).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index(
        "ix_domain_events_tenant_time", "domain_events", ["tenant_id", "occurred_at", "id"], unique=False
    )
    op.create_index(op.f("ix_tasks_reporter_id"), "tasks", ["reporter_id"], unique=False)
    op.create_index(
        "ix_tasks_title_trgm",
        "tasks",
        [sa.literal_column("lower(title) gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tasks_title_trgm",
        table_name="tasks",
        postgresql_using="gin",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_tasks_reporter_id"), table_name="tasks")
    op.drop_index("ix_domain_events_tenant_time", table_name="domain_events")
    # pg_trgm stays installed: other objects may use it, and it is harmless.
