"""project assistant

Revision ID: 1ac7d263f1cd
Revises: ef7d57c8887f
Create Date: 2026-10-09 18:58:28.651636+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "1ac7d263f1cd"
down_revision: str | Sequence[str] | None = "ef7d57c8887f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_briefs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_briefs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_project_briefs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_briefs")),
    )
    op.create_index(
        "ix_project_briefs_project_created", "project_briefs", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_project_briefs_tenant_id"), "project_briefs", ["tenant_id"], unique=False)
    op.create_table(
        "project_assistants",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("configured_by", sa.Uuid(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("digest_enabled", sa.Boolean(), nullable=False),
        sa.Column("digest_hour", sa.SmallInteger(), nullable=False),
        sa.Column("digest_minute", sa.SmallInteger(), nullable=False),
        sa.Column("weekdays_only", sa.Boolean(), nullable=False),
        sa.Column("weekly_enabled", sa.Boolean(), nullable=False),
        sa.Column("weekly_weekday", sa.SmallInteger(), nullable=False),
        sa.Column("weekly_hour", sa.SmallInteger(), nullable=False),
        sa.Column("stale_days", sa.Integer(), nullable=False),
        sa.Column("notify_in_app", sa.Boolean(), nullable=False),
        sa.Column("notify_email", sa.Boolean(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=True),
        sa.Column("next_digest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_weekly_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["integrations.id"],
            name=op.f("fk_project_assistants_channel_id_integrations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["configured_by"],
            ["users.id"],
            name=op.f("fk_project_assistants_configured_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_assistants_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_project_assistants_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_assistants")),
        sa.UniqueConstraint("project_id", name=op.f("uq_project_assistants_project_id")),
    )
    op.create_index(
        op.f("ix_project_assistants_next_digest_at"), "project_assistants", ["next_digest_at"], unique=False
    )
    op.create_index(
        op.f("ix_project_assistants_next_weekly_at"), "project_assistants", ["next_weekly_at"], unique=False
    )
    op.create_index(
        op.f("ix_project_assistants_tenant_id"), "project_assistants", ["tenant_id"], unique=False
    )
    op.add_column("users", sa.Column("kind", sa.String(length=20), server_default="person", nullable=False))
    # ### end Alembic commands ###
    enable_rls("project_assistants")
    enable_rls("project_briefs")
    op.execute("ALTER TYPE notification_kind ADD VALUE IF NOT EXISTS 'assistant'")


def downgrade() -> None:
    """Downgrade schema."""
    disable_rls("project_briefs")
    disable_rls("project_assistants")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "kind")
    op.drop_index(op.f("ix_project_assistants_tenant_id"), table_name="project_assistants")
    op.drop_index(op.f("ix_project_assistants_next_weekly_at"), table_name="project_assistants")
    op.drop_index(op.f("ix_project_assistants_next_digest_at"), table_name="project_assistants")
    op.drop_table("project_assistants")
    op.drop_index(op.f("ix_project_briefs_tenant_id"), table_name="project_briefs")
    op.drop_index("ix_project_briefs_project_created", table_name="project_briefs")
    op.drop_table("project_briefs")
    # ### end Alembic commands ###
