"""assistant suggestions

Revision ID: 6e7d0e53efda
Revises: 1ac7d263f1cd
Create Date: 2026-10-09 20:05:36.700880+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "6e7d0e53efda"
down_revision: str | Sequence[str] | None = "1ac7d263f1cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_suggestions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="open", nullable=False),
        sa.Column("reason", sa.String(length=500), server_default="", nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_assistant_suggestions_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_assistant_suggestions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_assistant_suggestions_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_assistant_suggestions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_suggestions")),
    )
    op.create_index(
        "ix_assistant_suggestions_project_status",
        "assistant_suggestions",
        ["project_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_suggestions_task_id"), "assistant_suggestions", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_assistant_suggestions_tenant_id"), "assistant_suggestions", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_assistant_suggestions_open",
        "assistant_suggestions",
        ["project_id", "dedupe_key"],
        unique=True,
        postgresql_where=sa.text("status = 'open' AND dedupe_key IS NOT NULL"),
    )
    op.add_column(
        "project_assistants",
        sa.Column("suggest", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###
    enable_rls("assistant_suggestions")


def downgrade() -> None:
    """Downgrade schema."""
    disable_rls("assistant_suggestions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_assistants", "suggest")
    op.drop_index(
        "uq_assistant_suggestions_open",
        table_name="assistant_suggestions",
        postgresql_where=sa.text("status = 'open' AND dedupe_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_assistant_suggestions_tenant_id"), table_name="assistant_suggestions")
    op.drop_index(op.f("ix_assistant_suggestions_task_id"), table_name="assistant_suggestions")
    op.drop_index("ix_assistant_suggestions_project_status", table_name="assistant_suggestions")
    op.drop_table("assistant_suggestions")
    # ### end Alembic commands ###
