"""dependencies baselines auto schedule

Revision ID: 9c3d6783f589
Revises: 48a8be0c2b50
Create Date: 2026-10-08 00:34:14.714963+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "9c3d6783f589"
down_revision: str | Sequence[str] | None = "48a8be0c2b50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


NEW_TABLES = ("task_dependencies", "baselines", "baseline_tasks")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baselines",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_baselines_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_baselines_project_id_projects"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_baselines_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baselines")),
    )
    op.create_index(op.f("ix_baselines_project_id"), "baselines", ["project_id"], unique=False)
    op.create_index(op.f("ix_baselines_tenant_id"), "baselines", ["tenant_id"], unique=False)
    op.create_table(
        "baseline_tasks",
        sa.Column("baseline_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_id"],
            ["baselines.id"],
            name=op.f("fk_baseline_tasks_baseline_id_baselines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_baseline_tasks_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_baseline_tasks_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("baseline_id", "task_id", name=op.f("pk_baseline_tasks")),
    )
    op.create_index(op.f("ix_baseline_tasks_tenant_id"), "baseline_tasks", ["tenant_id"], unique=False)
    op.create_table(
        "task_dependencies",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("predecessor_id", sa.Uuid(), nullable=False),
        sa.Column("successor_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("fs", "ss", "ff", "sf", name="dependency_type"), nullable=False),
        sa.Column("lag_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("predecessor_id <> successor_id", name=op.f("ck_task_dependencies_not_self")),
        sa.ForeignKeyConstraint(
            ["predecessor_id"],
            ["tasks.id"],
            name=op.f("fk_task_dependencies_predecessor_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_task_dependencies_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["successor_id"],
            ["tasks.id"],
            name=op.f("fk_task_dependencies_successor_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_task_dependencies_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_dependencies")),
        sa.UniqueConstraint(
            "predecessor_id", "successor_id", name=op.f("uq_task_dependencies_predecessor_id_successor_id")
        ),
    )
    op.create_index(
        op.f("ix_task_dependencies_predecessor_id"), "task_dependencies", ["predecessor_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_dependencies_project_id"), "task_dependencies", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_dependencies_successor_id"), "task_dependencies", ["successor_id"], unique=False
    )
    op.create_index(op.f("ix_task_dependencies_tenant_id"), "task_dependencies", ["tenant_id"], unique=False)
    op.add_column(
        "projects", sa.Column("auto_schedule", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###
    for table in NEW_TABLES:
        enable_rls(table)


def downgrade() -> None:
    """Downgrade schema."""
    for table in NEW_TABLES:
        disable_rls(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "auto_schedule")
    op.drop_index(op.f("ix_task_dependencies_tenant_id"), table_name="task_dependencies")
    op.drop_index(op.f("ix_task_dependencies_successor_id"), table_name="task_dependencies")
    op.drop_index(op.f("ix_task_dependencies_project_id"), table_name="task_dependencies")
    op.drop_index(op.f("ix_task_dependencies_predecessor_id"), table_name="task_dependencies")
    op.drop_table("task_dependencies")
    op.drop_index(op.f("ix_baseline_tasks_tenant_id"), table_name="baseline_tasks")
    op.drop_table("baseline_tasks")
    op.drop_index(op.f("ix_baselines_tenant_id"), table_name="baselines")
    op.drop_index(op.f("ix_baselines_project_id"), table_name="baselines")
    op.drop_table("baselines")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS dependency_type")
