"""saved reports

Revision ID: 7c54ac7de5d2
Revises: ab47e77e0d39
Create Date: 2026-10-09 13:01:46.706645+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "7c54ac7de5d2"
down_revision: str | Sequence[str] | None = "ab47e77e0d39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_reports",
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), server_default="", nullable=False),
        sa.Column("shared", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_saved_reports_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_saved_reports_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_reports")),
    )
    op.create_index(op.f("ix_saved_reports_owner_id"), "saved_reports", ["owner_id"], unique=False)
    op.create_index(op.f("ix_saved_reports_tenant_id"), "saved_reports", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    enable_rls("saved_reports")


def downgrade() -> None:
    """Downgrade schema."""
    disable_rls("saved_reports")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_reports_tenant_id"), table_name="saved_reports")
    op.drop_index(op.f("ix_saved_reports_owner_id"), table_name="saved_reports")
    op.drop_table("saved_reports")
    # ### end Alembic commands ###
