"""ai settings

Revision ID: 4264c5dbb4ae
Revises: 05f6d040d942
Create Date: 2026-10-08 18:29:21.913765+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4264c5dbb4ae"
down_revision: str | Sequence[str] | None = "05f6d040d942"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "org_settings", sa.Column("ai_enabled", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "org_settings",
        sa.Column(
            "ai_features",
            postgresql.ARRAY(sa.String(length=40)),
            server_default="{summaries,drafting,risks,search}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("org_settings", "ai_features")
    op.drop_column("org_settings", "ai_enabled")
    # ### end Alembic commands ###
