"""report alerts and notification links

Revision ID: fe53990766f9
Revises: c386c5964fc6
Create Date: 2026-10-09 15:59:39.658752+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "fe53990766f9"
down_revision: str | Sequence[str] | None = "c386c5964fc6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_alerts",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("measure", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("email", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("state", sa.String(length=10), server_default="unknown", nullable=False),
        sa.Column("last_value", sa.Float(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["saved_reports.id"],
            name=op.f("fk_report_alerts_report_id_saved_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_report_alerts_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_report_alerts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_alerts")),
        sa.UniqueConstraint("report_id", "user_id", name=op.f("uq_report_alerts_report_id_user_id")),
    )
    op.create_index(op.f("ix_report_alerts_next_run_at"), "report_alerts", ["next_run_at"], unique=False)
    op.create_index(op.f("ix_report_alerts_report_id"), "report_alerts", ["report_id"], unique=False)
    op.create_index(op.f("ix_report_alerts_tenant_id"), "report_alerts", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_report_alerts_user_id"), "report_alerts", ["user_id"], unique=False)
    op.add_column("notifications", sa.Column("link", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###
    enable_rls("report_alerts")
    op.execute("ALTER TYPE notification_kind ADD VALUE IF NOT EXISTS 'report_alert'")
    op.execute("ALTER TYPE notification_kind ADD VALUE IF NOT EXISTS 'system'")


def downgrade() -> None:
    """Downgrade schema. (The two notification kinds stay: Postgres cannot drop enum values.)"""
    disable_rls("report_alerts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "link")
    op.drop_index(op.f("ix_report_alerts_user_id"), table_name="report_alerts")
    op.drop_index(op.f("ix_report_alerts_tenant_id"), table_name="report_alerts")
    op.drop_index(op.f("ix_report_alerts_report_id"), table_name="report_alerts")
    op.drop_index(op.f("ix_report_alerts_next_run_at"), table_name="report_alerts")
    op.drop_table("report_alerts")
    # ### end Alembic commands ###
