"""channel posts

Revision ID: f6e06ddbd171
Revises: fe53990766f9
Create Date: 2026-10-09 16:28:54.205468+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "f6e06ddbd171"
down_revision: str | Sequence[str] | None = "fe53990766f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_posts",
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_channel_posts_created_by_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_channel_posts_integration_id_integrations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_channel_posts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["saved_reports.id"],
            name=op.f("fk_channel_posts_report_id_saved_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_channel_posts_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_posts")),
    )
    op.create_index(
        op.f("ix_channel_posts_integration_id"), "channel_posts", ["integration_id"], unique=False
    )
    op.create_index(op.f("ix_channel_posts_next_run_at"), "channel_posts", ["next_run_at"], unique=False)
    op.create_index(op.f("ix_channel_posts_tenant_id"), "channel_posts", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    enable_rls("channel_posts")


def downgrade() -> None:
    """Downgrade schema."""
    disable_rls("channel_posts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channel_posts_tenant_id"), table_name="channel_posts")
    op.drop_index(op.f("ix_channel_posts_next_run_at"), table_name="channel_posts")
    op.drop_index(op.f("ix_channel_posts_integration_id"), table_name="channel_posts")
    op.drop_table("channel_posts")
    # ### end Alembic commands ###
