"""governance sso scim integrations

Revision ID: 05f6d040d942
Revises: 3aad4b216ae9
Create Date: 2026-10-08 13:55:40.913247+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

NEW_RLS_TABLES = (
    "org_settings",
    "identity_providers",
    "user_identities",
    "integrations",
    "integration_deliveries",
)

# revision identifiers, used by Alembic.
revision: str = "05f6d040d942"
down_revision: str | Sequence[str] | None = "3aad4b216ae9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_providers",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("client_secret", sa.String(length=1000), nullable=True),
        sa.Column(
            "allowed_domains", postgresql.ARRAY(sa.String(length=253)), server_default="{}", nullable=False
        ),
        sa.Column("jit_provisioning", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("default_role", sa.String(length=20), server_default="member", nullable=False),
        sa.Column("enforce", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_identity_providers_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_providers")),
        sa.UniqueConstraint("tenant_id", "slug", name=op.f("uq_identity_providers_tenant_id_slug")),
    )
    op.create_index(
        op.f("ix_identity_providers_tenant_id"), "identity_providers", ["tenant_id"], unique=False
    )
    op.create_table(
        "org_settings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("audit_retention_days", sa.Integer(), server_default="365", nullable=False),
        sa.Column("activity_retention_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("notification_retention_days", sa.Integer(), server_default="90", nullable=False),
        sa.Column("deleted_task_retention_days", sa.Integer(), server_default="30", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_org_settings_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_org_settings")),
    )
    op.create_table(
        "calendar_feeds",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_calendar_feeds_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_calendar_feeds_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_feeds")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_calendar_feeds_token_hash")),
        sa.UniqueConstraint("user_id", name=op.f("uq_calendar_feeds_user_id")),
    )
    op.create_index(op.f("ix_calendar_feeds_tenant_id"), "calendar_feeds", ["tenant_id"], unique=False)
    op.create_table(
        "scim_tokens",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_scim_tokens_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_scim_tokens_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scim_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_scim_tokens_token_hash")),
    )
    op.create_index(op.f("ix_scim_tokens_tenant_id"), "scim_tokens", ["tenant_id"], unique=False)
    op.create_table(
        "user_identities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["identity_providers.id"],
            name=op.f("fk_user_identities_provider_id_identity_providers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_user_identities_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_identities_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint("provider_id", "subject", name=op.f("uq_user_identities_provider_id_subject")),
    )
    op.create_index(op.f("ix_user_identities_tenant_id"), "user_identities", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False)
    op.create_table(
        "integrations",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("events", postgresql.ARRAY(sa.String(length=100)), server_default="{}", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("secret", sa.String(length=2000), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_integrations_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_integrations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_integrations_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
    )
    op.create_index(op.f("ix_integrations_project_id"), "integrations", ["project_id"], unique=False)
    op.create_index(op.f("ix_integrations_tenant_id"), "integrations", ["tenant_id"], unique=False)
    op.create_table(
        "integration_deliveries",
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_integration_deliveries_integration_id_integrations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_deliveries_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_deliveries")),
        sa.UniqueConstraint(
            "integration_id", "event_id", name=op.f("uq_integration_deliveries_integration_id_event_id")
        ),
    )
    op.create_index(
        "ix_integration_deliveries_due",
        "integration_deliveries",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_integration_deliveries_integration",
        "integration_deliveries",
        ["integration_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_deliveries_tenant_id"), "integration_deliveries", ["tenant_id"], unique=False
    )
    op.add_column("users", sa.Column("external_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    for table in NEW_RLS_TABLES:
        enable_rls(table)


def downgrade() -> None:
    """Downgrade schema."""
    for table in NEW_RLS_TABLES:
        disable_rls(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "external_id")
    op.drop_index(op.f("ix_integration_deliveries_tenant_id"), table_name="integration_deliveries")
    op.drop_index("ix_integration_deliveries_integration", table_name="integration_deliveries")
    op.drop_index(
        "ix_integration_deliveries_due",
        table_name="integration_deliveries",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("integration_deliveries")
    op.drop_index(op.f("ix_integrations_tenant_id"), table_name="integrations")
    op.drop_index(op.f("ix_integrations_project_id"), table_name="integrations")
    op.drop_table("integrations")
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_tenant_id"), table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_index(op.f("ix_scim_tokens_tenant_id"), table_name="scim_tokens")
    op.drop_table("scim_tokens")
    op.drop_index(op.f("ix_calendar_feeds_tenant_id"), table_name="calendar_feeds")
    op.drop_table("calendar_feeds")
    op.drop_table("org_settings")
    op.drop_index(op.f("ix_identity_providers_tenant_id"), table_name="identity_providers")
    op.drop_table("identity_providers")
    # ### end Alembic commands ###
