"""session families and private manager view

Revision ID: f82419791756
Revises: 40f70796584f
Create Date: 2026-10-10 04:13:36.286286+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f82419791756"
down_revision: str | Sequence[str] | None = "40f70796584f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_sessions", sa.Column("family_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_auth_sessions_family_id"), "auth_sessions", ["family_id"], unique=False)
    # My team: managers see only projects they can open unless an admin widens it. Nobody has chosen
    # yet (0.21.0 shipped hours before), so existing organizations move to the private default too.
    op.alter_column("org_settings", "manager_visibility", server_default="shared")
    op.execute("UPDATE org_settings SET manager_visibility = 'shared'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("org_settings", "manager_visibility", server_default="all")
    op.drop_index(op.f("ix_auth_sessions_family_id"), table_name="auth_sessions")
    op.drop_column("auth_sessions", "family_id")
    # ### end Alembic commands ###
