"""automation rules runs recurring templates

Revision ID: b0c09c2af5c3
Revises: 9c3d6783f589
Create Date: 2026-10-08 01:21:54.106692+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "b0c09c2af5c3"
down_revision: str | Sequence[str] | None = "9c3d6783f589"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NEW_TABLES = ("automation_rules", "automation_runs", "recurring_tasks", "project_templates")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_templates",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), server_default="", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_project_templates_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_project_templates_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_templates")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_project_templates_tenant_id_name")),
    )
    op.create_index(op.f("ix_project_templates_tenant_id"), "project_templates", ["tenant_id"], unique=False)
    op.create_table(
        "automation_rules",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("trigger_type", sa.String(length=40), nullable=False),
        sa.Column("trigger", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_on_automation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("webhook_secret", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_automation_rules_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_automation_rules_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_automation_rules_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_rules")),
    )
    op.create_index(
        op.f("ix_automation_rules_next_run_at"), "automation_rules", ["next_run_at"], unique=False
    )
    op.create_index(
        "ix_automation_rules_project_enabled", "automation_rules", ["project_id", "enabled"], unique=False
    )
    op.create_index(op.f("ix_automation_rules_tenant_id"), "automation_rules", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_automation_rules_trigger_type"), "automation_rules", ["trigger_type"], unique=False
    )
    op.create_table(
        "automation_runs",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("trigger_type", sa.String(length=40), nullable=False),
        sa.Column(
            "status", sa.Enum("success", "failed", "skipped", name="automation_run_status"), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_automation_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["automation_rules.id"],
            name=op.f("fk_automation_runs_rule_id_automation_rules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_automation_runs_task_id_tasks"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_automation_runs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_runs")),
        sa.UniqueConstraint("rule_id", "dedupe_key", name=op.f("uq_automation_runs_rule_id_dedupe_key")),
    )
    op.create_index(
        "ix_automation_runs_project_started", "automation_runs", ["project_id", "started_at"], unique=False
    )
    op.create_index(
        "ix_automation_runs_task_started", "automation_runs", ["task_id", "started_at"], unique=False
    )
    op.create_index(op.f("ix_automation_runs_tenant_id"), "automation_runs", ["tenant_id"], unique=False)
    op.create_table(
        "recurring_tasks",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("template", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_task_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_recurring_tasks_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_task_id"],
            ["tasks.id"],
            name=op.f("fk_recurring_tasks_last_task_id_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_recurring_tasks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_recurring_tasks_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_tasks")),
    )
    op.create_index(op.f("ix_recurring_tasks_next_run_at"), "recurring_tasks", ["next_run_at"], unique=False)
    op.create_index(op.f("ix_recurring_tasks_project_id"), "recurring_tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_recurring_tasks_tenant_id"), "recurring_tasks", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    for table in NEW_TABLES:
        enable_rls(table)
    op.execute("ALTER TYPE notification_kind ADD VALUE IF NOT EXISTS 'automation'")


def downgrade() -> None:
    """Downgrade schema."""
    # Enum values cannot be dropped in place; remove the rows that use it and keep the label.
    op.execute("DELETE FROM notifications WHERE kind = 'automation'")
    for table in NEW_TABLES:
        disable_rls(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recurring_tasks_tenant_id"), table_name="recurring_tasks")
    op.drop_index(op.f("ix_recurring_tasks_project_id"), table_name="recurring_tasks")
    op.drop_index(op.f("ix_recurring_tasks_next_run_at"), table_name="recurring_tasks")
    op.drop_table("recurring_tasks")
    op.drop_index(op.f("ix_automation_runs_tenant_id"), table_name="automation_runs")
    op.drop_index("ix_automation_runs_project_started", table_name="automation_runs")
    op.drop_index("ix_automation_runs_task_started", table_name="automation_runs")
    op.drop_table("automation_runs")
    op.drop_index(op.f("ix_automation_rules_trigger_type"), table_name="automation_rules")
    op.drop_index(op.f("ix_automation_rules_tenant_id"), table_name="automation_rules")
    op.drop_index("ix_automation_rules_project_enabled", table_name="automation_rules")
    op.drop_index(op.f("ix_automation_rules_next_run_at"), table_name="automation_rules")
    op.drop_table("automation_rules")
    op.drop_index(op.f("ix_project_templates_tenant_id"), table_name="project_templates")
    op.drop_table("project_templates")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS automation_run_status")
