"""fields comments notifications views

Revision ID: 48a8be0c2b50
Revises: fc574a389a24
Create Date: 2026-10-07 23:51:28.035332+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "48a8be0c2b50"
down_revision: str | Sequence[str] | None = "fc574a389a24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


NEW_TABLES = ("custom_fields", "comments", "notifications", "saved_views")
ENUMS = ("field_type", "view_kind", "notification_kind")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_fields",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "text",
                "number",
                "date",
                "select",
                "multi_select",
                "user",
                "checkbox",
                "url",
                name="field_type",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=500), server_default="", nullable=False),
        sa.Column("required", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_custom_fields_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_custom_fields_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_fields")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_custom_fields_project_id_name")),
    )
    op.create_index(op.f("ix_custom_fields_project_id"), "custom_fields", ["project_id"], unique=False)
    op.create_index(op.f("ix_custom_fields_tenant_id"), "custom_fields", ["tenant_id"], unique=False)
    op.create_table(
        "saved_views",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("list", "board", "table", "timeline", "calendar", name="view_kind"),
            nullable=False,
        ),
        sa.Column("shared", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_saved_views_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_saved_views_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_saved_views_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_views")),
    )
    op.create_index(op.f("ix_saved_views_owner_id"), "saved_views", ["owner_id"], unique=False)
    op.create_index("ix_saved_views_project", "saved_views", ["project_id", "position"], unique=False)
    op.create_index(op.f("ix_saved_views_tenant_id"), "saved_views", ["tenant_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("mentions", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_comments_author_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_comments_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_comments_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index("ix_comments_task_created", "comments", ["task_id", "created_at"], unique=False)
    op.create_index(op.f("ix_comments_tenant_id"), "comments", ["tenant_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind", sa.Enum("mention", "assigned", "comment", name="notification_kind"), nullable=False
        ),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_notifications_actor_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_notifications_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_notifications_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_notifications_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("event_id", "user_id", name=op.f("uq_notifications_event_id_user_id")),
    )
    op.create_index(op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False)
    op.create_index("ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False)
    op.create_index(
        "ix_notifications_user_unread",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.add_column("domain_events", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.create_index("ix_domain_events_project", "domain_events", ["project_id", "occurred_at"], unique=False)
    op.add_column(
        "tasks",
        sa.Column(
            "custom_fields", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.create_index(
        "ix_tasks_custom_fields", "tasks", ["custom_fields"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###
    for table in NEW_TABLES:
        enable_rls(table)
    # Backfill the project of existing events so project activity feeds include history.
    op.execute("UPDATE domain_events SET project_id = aggregate_id WHERE aggregate_type = 'project'")
    op.execute(
        "UPDATE domain_events SET project_id = (payload #>> '{task,project_id}')::uuid "
        "WHERE aggregate_type = 'task' AND payload #>> '{task,project_id}' IS NOT NULL"
    )
    op.execute(
        "UPDATE domain_events e SET project_id = t.project_id FROM tasks t "
        "WHERE e.aggregate_type = 'task' AND e.project_id IS NULL AND t.id = e.aggregate_id"
    )


def downgrade() -> None:
    """Downgrade schema."""
    for table in NEW_TABLES:
        disable_rls(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_custom_fields", table_name="tasks", postgresql_using="gin")
    op.drop_column("tasks", "custom_fields")
    op.drop_index("ix_domain_events_project", table_name="domain_events")
    op.drop_column("domain_events", "project_id")
    op.drop_index(
        "ix_notifications_user_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_comments_tenant_id"), table_name="comments")
    op.drop_index("ix_comments_task_created", table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_saved_views_tenant_id"), table_name="saved_views")
    op.drop_index("ix_saved_views_project", table_name="saved_views")
    op.drop_index(op.f("ix_saved_views_owner_id"), table_name="saved_views")
    op.drop_table("saved_views")
    op.drop_index(op.f("ix_custom_fields_tenant_id"), table_name="custom_fields")
    op.drop_index(op.f("ix_custom_fields_project_id"), table_name="custom_fields")
    op.drop_table("custom_fields")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
