"""web push

Revision ID: ef7d57c8887f
Revises: f6e06ddbd171
Create Date: 2026-10-09 17:28:28.496125+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "ef7d57c8887f"
down_revision: str | Sequence[str] | None = "f6e06ddbd171"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.String(length=1000), nullable=False),
        sa.Column("p256dh", sa.String(length=200), nullable=False),
        sa.Column("auth", sa.String(length=100), nullable=False),
        sa.Column("device", sa.String(length=200), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_push_subscriptions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_push_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_push_subscriptions_endpoint")),
    )
    op.create_index(
        op.f("ix_push_subscriptions_tenant_id"), "push_subscriptions", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False)
    op.add_column("notifications", sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "ix_notifications_unpushed",
        "notifications",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("pushed_at IS NULL"),
    )
    # ### end Alembic commands ###
    enable_rls("push_subscriptions")


def downgrade() -> None:
    """Downgrade schema."""
    disable_rls("push_subscriptions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notifications_unpushed", table_name="notifications", postgresql_where=sa.text("pushed_at IS NULL")
    )
    op.drop_column("notifications", "pushed_at")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_index(op.f("ix_push_subscriptions_tenant_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    # ### end Alembic commands ###
