"""time tracking workload dashboards portfolios okrs

Revision ID: d6b325a0ccbf
Revises: b0c09c2af5c3
Create Date: 2026-10-08 04:09:22.920443+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from glasshaus.migrations.helpers import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "d6b325a0ccbf"
down_revision: str | Sequence[str] | None = "b0c09c2af5c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NEW_TABLES = (
    "time_entries",
    "running_timers",
    "dashboards",
    "portfolios",
    "portfolio_projects",
    "objectives",
    "key_results",
    "kr_check_ins",
)
ENUMS = ("key_result_kind", "kr_confidence")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("shared", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("widgets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_dashboards_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_dashboards_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboards")),
    )
    op.create_index(op.f("ix_dashboards_owner_id"), "dashboards", ["owner_id"], unique=False)
    op.create_index(op.f("ix_dashboards_tenant_id"), "dashboards", ["tenant_id"], unique=False)
    op.create_table(
        "objectives",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_objectives_owner_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["objectives.id"],
            name=op.f("fk_objectives_parent_id_objectives"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_objectives_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objectives")),
    )
    op.create_index("ix_objectives_period", "objectives", ["tenant_id", "period"], unique=False)
    op.create_index(op.f("ix_objectives_tenant_id"), "objectives", ["tenant_id"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), server_default="", nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_portfolios_owner_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_portfolios_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
    )
    op.create_index(op.f("ix_portfolios_tenant_id"), "portfolios", ["tenant_id"], unique=False)
    op.create_table(
        "key_results",
        sa.Column("objective_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.Enum("metric", "tasks", name="key_result_kind"), nullable=False),
        sa.Column("unit", sa.String(length=20), server_default="", nullable=False),
        sa.Column("start_value", sa.Float(), server_default="0", nullable=False),
        sa.Column("target_value", sa.Float(), server_default="100", nullable=False),
        sa.Column("current_value", sa.Float(), server_default="0", nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("tag", sa.String(length=50), nullable=True),
        sa.Column("weight", sa.Float(), server_default="1", nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column(
            "confidence", sa.Enum("on_track", "at_risk", "off_track", name="kr_confidence"), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("weight > 0", name=op.f("ck_key_results_weight_positive")),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_key_results_objective_id_objectives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_key_results_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_key_results_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_key_results")),
    )
    op.create_index(op.f("ix_key_results_objective_id"), "key_results", ["objective_id"], unique=False)
    op.create_index(op.f("ix_key_results_tenant_id"), "key_results", ["tenant_id"], unique=False)
    op.create_table(
        "portfolio_projects",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_projects_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_portfolio_projects_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_portfolio_projects_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("portfolio_id", "project_id", name=op.f("pk_portfolio_projects")),
    )
    op.create_index(
        op.f("ix_portfolio_projects_project_id"), "portfolio_projects", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_projects_tenant_id"), "portfolio_projects", ["tenant_id"], unique=False
    )
    op.create_table(
        "kr_check_ins",
        sa.Column("key_result_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column(
            "confidence", sa.Enum("on_track", "at_risk", "off_track", name="kr_confidence"), nullable=False
        ),
        sa.Column("note", sa.String(length=2000), server_default="", nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_kr_check_ins_author_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["key_result_id"],
            ["key_results.id"],
            name=op.f("fk_kr_check_ins_key_result_id_key_results"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_kr_check_ins_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kr_check_ins")),
    )
    op.create_index(op.f("ix_kr_check_ins_key_result_id"), "kr_check_ins", ["key_result_id"], unique=False)
    op.create_index(op.f("ix_kr_check_ins_tenant_id"), "kr_check_ins", ["tenant_id"], unique=False)
    op.create_table(
        "running_timers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=500), server_default="", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_running_timers_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_running_timers_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_running_timers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_running_timers")),
    )
    op.create_index(op.f("ix_running_timers_tenant_id"), "running_timers", ["tenant_id"], unique=False)
    op.create_table(
        "time_entries",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("spent_on", sa.Date(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=500), server_default="", nullable=False),
        sa.Column("billable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_time_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_time_entries_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_time_entries_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_time_entries_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_entries")),
    )
    op.create_index("ix_time_entries_project_day", "time_entries", ["project_id", "spent_on"], unique=False)
    op.create_index(op.f("ix_time_entries_task_id"), "time_entries", ["task_id"], unique=False)
    op.create_index(op.f("ix_time_entries_tenant_id"), "time_entries", ["tenant_id"], unique=False)
    op.create_index("ix_time_entries_user_day", "time_entries", ["user_id", "spent_on"], unique=False)
    op.add_column("users", sa.Column("capacity_minutes", sa.Integer(), server_default="480", nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "working_days", postgresql.ARRAY(sa.SmallInteger()), server_default="{0,1,2,3,4}", nullable=False
        ),
    )
    # ### end Alembic commands ###
    for table in NEW_TABLES:
        enable_rls(table)


def downgrade() -> None:
    """Downgrade schema."""
    for table in NEW_TABLES:
        disable_rls(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "working_days")
    op.drop_column("users", "capacity_minutes")
    op.drop_index("ix_time_entries_user_day", table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_tenant_id"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_task_id"), table_name="time_entries")
    op.drop_index("ix_time_entries_project_day", table_name="time_entries")
    op.drop_table("time_entries")
    op.drop_index(op.f("ix_running_timers_tenant_id"), table_name="running_timers")
    op.drop_table("running_timers")
    op.drop_index(op.f("ix_kr_check_ins_tenant_id"), table_name="kr_check_ins")
    op.drop_index(op.f("ix_kr_check_ins_key_result_id"), table_name="kr_check_ins")
    op.drop_table("kr_check_ins")
    op.drop_index(op.f("ix_portfolio_projects_tenant_id"), table_name="portfolio_projects")
    op.drop_index(op.f("ix_portfolio_projects_project_id"), table_name="portfolio_projects")
    op.drop_table("portfolio_projects")
    op.drop_index(op.f("ix_key_results_tenant_id"), table_name="key_results")
    op.drop_index(op.f("ix_key_results_objective_id"), table_name="key_results")
    op.drop_table("key_results")
    op.drop_index(op.f("ix_portfolios_tenant_id"), table_name="portfolios")
    op.drop_table("portfolios")
    op.drop_index(op.f("ix_objectives_tenant_id"), table_name="objectives")
    op.drop_index("ix_objectives_period", table_name="objectives")
    op.drop_table("objectives")
    op.drop_index(op.f("ix_dashboards_tenant_id"), table_name="dashboards")
    op.drop_index(op.f("ix_dashboards_owner_id"), table_name="dashboards")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
