"""assistant trusted actions

Revision ID: 2f9c61b24281
Revises: 6e7d0e53efda
Create Date: 2026-10-09 20:55:56.794677+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f9c61b24281"
down_revision: str | Sequence[str] | None = "6e7d0e53efda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "org_settings",
        sa.Column(
            "assistant_trusted", postgresql.ARRAY(sa.String(length=20)), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "project_assistants",
        sa.Column("trusted", postgresql.ARRAY(sa.String(length=20)), server_default="{}", nullable=False),
    )
    op.add_column(
        "project_assistants", sa.Column("auto_daily_cap", sa.Integer(), server_default="10", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_assistants", "auto_daily_cap")
    op.drop_column("project_assistants", "trusted")
    op.drop_column("org_settings", "assistant_trusted")
    # ### end Alembic commands ###
