/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: operations['healthz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readyz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness probe (database and Redis) */
    get: operations['readyz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Running version */
    get: operations['get_version'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign in with email and password (sets session cookies) */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the session using the refresh cookie */
    post: operations['refresh_session'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** End the session */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change your password (ends sessions) */
    post: operations['change_password'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The authenticated user */
    get: operations['get_current_user'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users in the organization */
    get: operations['list_users'];
    put?: never;
    /** Create a user */
    post: operations['create_user'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update a user's name, role or status */
    patch: operations['update_user'];
    trace?: never;
  };
  '/api/v1/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List your API tokens */
    get: operations['list_api_tokens'];
    put?: never;
    /** Create an API token (the secret is returned once) */
    post: operations['create_api_token'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tokens/{token_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a token */
    delete: operations['revoke_api_token'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workspaces you can see */
    get: operations['list_workspaces'];
    put?: never;
    /** Create a workspace */
    post: operations['create_workspace'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a workspace */
    get: operations['get_workspace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update a workspace */
    patch: operations['update_workspace'];
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workspace members */
    get: operations['list_workspace_members'];
    /** Add or change a member */
    put: operations['set_workspace_member'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/members/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a member */
    delete: operations['remove_workspace_member'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List projects you can see */
    get: operations['list_projects'];
    put?: never;
    /** Create a project */
    post: operations['create_project'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/by-key/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a project by its key */
    get: operations['get_project_by_key'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a project with its statuses */
    get: operations['get_project'];
    put?: never;
    post?: never;
    /** Delete a project and its tasks (dry_run=true, the default, only previews) */
    delete: operations['delete_project'];
    options?: never;
    head?: never;
    /** Update or archive a project */
    patch: operations['update_project'];
    trace?: never;
  };
  '/api/v1/projects/{project_id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List project members */
    get: operations['list_project_members'];
    /** Add or change a project member */
    put: operations['set_project_member'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/members/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a project member */
    delete: operations['remove_project_member'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/statuses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workflow statuses */
    get: operations['list_statuses'];
    put?: never;
    /** Add a status */
    post: operations['create_status'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/statuses/{status_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a status, moving its tasks to replacement_status_id */
    delete: operations['delete_status'];
    options?: never;
    head?: never;
    /** Update a status */
    patch: operations['update_status'];
    trace?: never;
  };
  '/api/v1/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search and list tasks */
    get: operations['list_tasks'];
    put?: never;
    /** Create a task */
    post: operations['create_task'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/bulk-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply one change to many tasks */
    post: operations['bulk_update_tasks'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/bulk-delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete tasks and their subtasks (dry_run=true, the default, only previews) */
    post: operations['bulk_delete_tasks'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{ref}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a task by id or reference (e.g. WEB-12) */
    get: operations['get_task'];
    put?: never;
    post?: never;
    /** Delete a task and its subtasks */
    delete: operations['delete_task'];
    options?: never;
    head?: never;
    /** Update a task (supports If-Match) */
    patch: operations['update_task'];
    trace?: never;
  };
  '/api/v1/tasks/{ref}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore a deleted task */
    post: operations['restore_task'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{ref}/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Your permissions on a task */
    get: operations['get_task_permissions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApiTokenCreate */
    ApiTokenCreate: {
      /** Name */
      name: string;
      /** Scopes */
      scopes: components['schemas']['Scope'][];
      /**
       * Expires In Days
       * @description null for a non-expiring token
       * @default 90
       */
      expires_in_days?: number | null;
    };
    /** ApiTokenCreated */
    ApiTokenCreated: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Prefix */
      prefix: string;
      /** Scopes */
      scopes: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /** Last Used At */
      last_used_at: string | null;
      /** Revoked At */
      revoked_at: string | null;
      /**
       * Token
       * @description The secret. Shown once; store it securely.
       */
      token: string;
    };
    /** ApiTokenRead */
    ApiTokenRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Prefix */
      prefix: string;
      /** Scopes */
      scopes: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /** Last Used At */
      last_used_at: string | null;
      /** Revoked At */
      revoked_at: string | null;
    };
    /** BulkResult */
    BulkResult: {
      /** Updated */
      updated: string[];
      /** Failed */
      failed?: {
        [key: string]: string;
      };
    };
    /**
     * DeletePreview
     * @description Returned by destructive operations when dry_run=true (and as the result when executed).
     */
    DeletePreview: {
      /** Resource */
      resource: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Executed */
      executed: boolean;
      /**
       * Affected
       * @description Counts of dependent records that are removed as well.
       */
      affected: {
        [key: string]: number;
      };
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /**
       * Organization
       * @description Organization slug; defaults to the default tenant.
       */
      organization?: string | null;
    };
    /**
     * OrgRole
     * @enum {string}
     */
    OrgRole: 'owner' | 'admin' | 'member' | 'guest';
    /** Page[TaskRead] */
    Page_TaskRead_: {
      /** Items */
      items: components['schemas']['TaskRead'][];
      /**
       * Next Cursor
       * @description Opaque cursor for the next page; null when done.
       */
      next_cursor?: string | null;
    };
    /** PasswordChange */
    PasswordChange: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /**
     * Priority
     * @enum {string}
     */
    Priority: 'none' | 'low' | 'medium' | 'high' | 'urgent';
    /** Problem */
    Problem: {
      /** Type */
      type: string;
      /** Title */
      title: string;
      /** Status */
      status: number;
      /** Detail */
      detail: string;
      /** Code */
      code: string;
      /** Errors */
      errors?:
        | {
            [key: string]: unknown;
          }[]
        | null;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string;
      /**
       * Key
       * @description Short uppercase key used in task references, e.g. WEB-12.
       */
      key: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description?: string;
    };
    /** ProjectDetail */
    ProjectDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string;
      /** Key */
      key: string;
      /** Name */
      name: string;
      /** Description */
      description: string;
      /** Archived At */
      archived_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** @description The caller's effective role on this project. */
      my_role?: components['schemas']['ProjectRole'] | null;
      /** Statuses */
      statuses: components['schemas']['StatusRead'][];
    };
    /** ProjectMemberRead */
    ProjectMemberRead: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      role: components['schemas']['ProjectRole'];
    };
    /** ProjectMemberSet */
    ProjectMemberSet: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      role: components['schemas']['ProjectRole'];
    };
    /** ProjectRead */
    ProjectRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string;
      /** Key */
      key: string;
      /** Name */
      name: string;
      /** Description */
      description: string;
      /** Archived At */
      archived_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** @description The caller's effective role on this project. */
      my_role?: components['schemas']['ProjectRole'] | null;
    };
    /**
     * ProjectRole
     * @enum {string}
     */
    ProjectRole: 'admin' | 'editor' | 'commenter' | 'viewer';
    /** ProjectUpdate */
    ProjectUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Archived */
      archived?: boolean | null;
    };
    /** Readiness */
    Readiness: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      /** Checks */
      checks: {
        [key: string]: string;
      };
    };
    /**
     * Scope
     * @description OAuth-style scopes for API tokens (and, from Phase 6, MCP clients).
     * @enum {string}
     */
    Scope: 'read' | 'tasks:write' | 'projects:write' | 'admin';
    /**
     * StatusCategory
     * @enum {string}
     */
    StatusCategory: 'backlog' | 'todo' | 'in_progress' | 'done' | 'cancelled';
    /** StatusCreate */
    StatusCreate: {
      /** Name */
      name: string;
      category: components['schemas']['StatusCategory'];
      /**
       * Color
       * @default #64748b
       */
      color?: string;
      /** Position */
      position?: number | null;
    };
    /** StatusRead */
    StatusRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      category: components['schemas']['StatusCategory'];
      /** Color */
      color: string;
      /** Position */
      position: number;
    };
    /** StatusUpdate */
    StatusUpdate: {
      /** Name */
      name?: string | null;
      category?: components['schemas']['StatusCategory'] | null;
      /** Color */
      color?: string | null;
      /** Position */
      position?: number | null;
    };
    /** TaskBulkPatch */
    TaskBulkPatch: {
      /** Status Id */
      status_id?: string | null;
      /** @description Move each task to its project's first status in this category (works across projects). */
      status_category?: components['schemas']['StatusCategory'] | null;
      priority?: components['schemas']['Priority'] | null;
      /** Assignee Id */
      assignee_id?: string | null;
      /** Due Date */
      due_date?: string | null;
      /** Add Tags */
      add_tags?: string[];
      /** Remove Tags */
      remove_tags?: string[];
    };
    /** TaskBulkUpdate */
    TaskBulkUpdate: {
      /** Task Ids */
      task_ids: string[];
      patch: components['schemas']['TaskBulkPatch'];
    };
    /** TaskCreate */
    TaskCreate: {
      /** Start Date */
      start_date?: string | null;
      /** Due Date */
      due_date?: string | null;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Title */
      title: string;
      /**
       * Description
       * @description Markdown. Treated as untrusted content.
       * @default
       */
      description?: string;
      /**
       * Status Id
       * @description Defaults to the project's first 'todo' status.
       */
      status_id?: string | null;
      /** @default none */
      priority?: components['schemas']['Priority'];
      /** Assignee Id */
      assignee_id?: string | null;
      /** Parent Id */
      parent_id?: string | null;
      /** Estimate Minutes */
      estimate_minutes?: number | null;
      /** Tags */
      tags?: string[];
      /** Position */
      position?: number | null;
    };
    /** TaskIds */
    TaskIds: {
      /** Task Ids */
      task_ids: string[];
    };
    /** TaskRead */
    TaskRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Key
       * @description Human reference, e.g. WEB-12
       */
      key: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Number */
      number: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      status: components['schemas']['StatusRead'];
      priority: components['schemas']['Priority'];
      /** Assignee Id */
      assignee_id: string | null;
      /** Reporter Id */
      reporter_id: string | null;
      /** Parent Id */
      parent_id: string | null;
      /** Start Date */
      start_date: string | null;
      /** Due Date */
      due_date: string | null;
      /** Estimate Minutes */
      estimate_minutes: number | null;
      /** Tags */
      tags: string[];
      /** Position */
      position: number;
      /** Completed At */
      completed_at: string | null;
      /** Deleted At */
      deleted_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version */
      version: number;
    };
    /**
     * TaskSort
     * @enum {string}
     */
    TaskSort: 'position' | 'created_at' | 'updated_at' | 'due_date' | 'priority' | 'number' | 'title';
    /** TaskUpdate */
    TaskUpdate: {
      /** Start Date */
      start_date?: string | null;
      /** Due Date */
      due_date?: string | null;
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Status Id */
      status_id?: string | null;
      priority?: components['schemas']['Priority'] | null;
      /** Assignee Id */
      assignee_id?: string | null;
      /** Parent Id */
      parent_id?: string | null;
      /** Estimate Minutes */
      estimate_minutes?: number | null;
      /** Tags */
      tags?: string[] | null;
      /** Position */
      position?: number | null;
      /**
       * Expected Version
       * @description Optimistic concurrency: fail with 412 if changed.
       */
      expected_version?: number | null;
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Name */
      name: string;
      /** Password */
      password?: string | null;
      /** @default member */
      org_role?: components['schemas']['OrgRole'];
    };
    /** UserRead */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Name */
      name: string;
      org_role: components['schemas']['OrgRole'];
      /** Is Active */
      is_active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Last Login At */
      last_login_at: string | null;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Name */
      name?: string | null;
      org_role?: components['schemas']['OrgRole'] | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /** VersionInfo */
    VersionInfo: {
      /**
       * Name
       * @default Project Glasshaus
       */
      name?: string;
      /** Version */
      version: string;
      /** Build */
      build: string;
    };
    /** WorkspaceCreate */
    WorkspaceCreate: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Description
       * @default
       */
      description?: string;
    };
    /** WorkspaceMemberRead */
    WorkspaceMemberRead: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      role: components['schemas']['WorkspaceRole'];
    };
    /** WorkspaceMemberSet */
    WorkspaceMemberSet: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      role: components['schemas']['WorkspaceRole'];
    };
    /** WorkspaceRead */
    WorkspaceRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Description */
      description: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * WorkspaceRole
     * @enum {string}
     */
    WorkspaceRole: 'admin' | 'member' | 'viewer';
    /** WorkspaceUpdate */
    WorkspaceUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  readyz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Readiness'];
        };
      };
    };
  };
  get_version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionInfo'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  refresh_session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  change_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChange'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_current_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_users: {
    parameters: {
      query?: {
        q?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'][];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  create_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  update_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_api_tokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiTokenRead'][];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  create_api_token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ApiTokenCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiTokenCreated'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  revoke_api_token: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_workspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceRead'][];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  create_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  update_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_workspace_members: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceMemberRead'][];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  set_workspace_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceMemberSet'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceMemberRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  remove_workspace_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_projects: {
    parameters: {
      query?: {
        workspace_id?: string | null;
        include_archived?: boolean;
        q?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectRead'][];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  create_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectDetail'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_project_by_key: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectDetail'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectDetail'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  delete_project: {
    parameters: {
      query?: {
        dry_run?: boolean;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletePreview'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  update_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectDetail'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_project_members: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectMemberRead'][];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  set_project_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectMemberSet'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectMemberRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  remove_project_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_statuses: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusRead'][];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  create_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StatusCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  delete_status: {
    parameters: {
      query?: {
        replacement_status_id?: string | null;
      };
      header?: never;
      path: {
        project_id: string;
        status_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  update_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        status_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StatusUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_tasks: {
    parameters: {
      query?: {
        project_id?: string | null;
        workspace_id?: string | null;
        status_ids?: string[] | null;
        status_categories?: components['schemas']['StatusCategory'][] | null;
        assignee_ids?: string[] | null;
        unassigned?: boolean | null;
        priorities?: components['schemas']['Priority'][] | null;
        parent_id?: string | null;
        top_level_only?: boolean;
        /** @description Tasks having all of these tags. */
        tags?: string[] | null;
        /** @description Text search on key and title. */
        q?: string | null;
        due_before?: string | null;
        due_after?: string | null;
        updated_since?: string | null;
        include_deleted?: boolean;
        sort?: components['schemas']['TaskSort'];
        descending?: boolean;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_TaskRead_'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  create_task: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  bulk_update_tasks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskBulkUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BulkResult'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  bulk_delete_tasks: {
    parameters: {
      query?: {
        dry_run?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskIds'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletePreview'][];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_task: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  delete_task: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  update_task: {
    parameters: {
      query?: never;
      header?: {
        'if-match'?: string | null;
      };
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  restore_task: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskRead'];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_task_permissions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string[];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Invalid input */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': unknown;
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
}
